
project_id = "npjkzyyfkqcskpguugcv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true
double_confirm_changes = true
double_confirm_deletions = true

[auth.email.template.invite]

[auth.sms]
enabled = true

[analytics]
enabled = true
port = 54327

[experimental]
enabled = false

[ai]
enabled = true

[edge_functions]
enabled = true

[functions.analyze-wallet]
verify_jwt = false

[functions.analyze-market]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

