
project_id = "your-project-id"

[functions.ai-chat]
verify_jwt = true

[functions.analyze-market]
verify_jwt = true

[functions.analyze-wallet]
verify_jwt = true

[functions.check-api-keys]
verify_jwt = true

[functions.twitter-api]
verify_jwt = true
