// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npjkzyyfkqcskpguugcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wamt6eXlma3Fjc2twZ3V1Z2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODA5MjEsImV4cCI6MjA2MzA1NjkyMX0.feDlff0KuJWDrlDhvq0xwCgL9ym5OzPBRrXbJ2CBTTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);